[build]
command = "npm run build"
functions = "out_functions"
publish = "out_publish"

[build.environment]
NODE_VERSION = "14"

[[plugins]]
package = "@netlify/plugin-nextjs"
PLASMIC_AUTH_TOKEN = "Vo34wuGS4sZpEjV0bu5MQK7Z3qlrnmNy9rICNaz6cfdZMIhDlHK4KfmZflUY0AZJHiAa5dEZXlQddkK1cog"